### ISSUE TITLE
Issue building project in m1

### ISSUE THREAD

**Issue by RahulMukherjee** [Tealium/tealium-ios-firebase-remote-command#13]
We are migrating our project to m1 machine and trying to build it without Rosetta enabled. During building the project, we found that on adding TealiumFirebase as pod dependency the arm64 is getting added in Excluded Architecture(Any iOS Simulator SDK) in main project automatically. 
This is not allowing us to build the project in m1 without Rosetta since we have other SPMs also which were failing to build as arm64 is present in Excluded Architecture(Any iOS Simulator SDK). 
Any suggestion or any upcoming update to fix this issue?

<img width="829" alt="Screenshot 2023-01-04 at 10 52 57 AM" src="https://user-images.githubusercontent.com/10434289/210489636-af43fee2-5ff0-4a46-a216-3d03ebb23634.png">

**Comment by Enricoza** [comment]
Hi @RahulMukherjee sorry for the late reply. We are working on this and after the update you will be able to use it without any problems.
At the moment as a workaround you can just change the project settings after the `pod install` or add a post install script to do that automatically.

**Comment by Enricoza** [comment]
Hi @RahulMukherjee, with version `2.3.0` you should be able to now install on an M1 machine without any workarounds.
Thanks again for your patience and let us know if you have any more problems.
